### ISSUE TITLE
Linux on XuLA2?

### ISSUE THREAD

**Issue by lollisoft** [xesscorp/XuLA2#1]
Are there any hints or attempts for Linux on XuLA2?

I've read something about the toolchain and a kernel. So it may be a starting point.

Before I buy such a board, I like to know if Linux can be made running on this board.

Thanks, Lothar

**Comment by tommythorn** [comment]
Is this still an issue?  I'm using my XuLA2-lx25 exclusively from both Linux and Mac OS X, the latter requires running ISE in a Linux VM but the XSTOOLs runs natively under either.

**Comment by lollisoft** [comment]
Yes,

I am generally interested into running linux on that device. Do you have more informations / a working design?

Thanks, Lothar

Am 03.07.2015 um 20:23 schrieb Tommy Thorn:

**Comment by tommythorn** [comment]
Sorry, I misunderstood.  I don't have Linux running yet, but my YARVI will evolve to support the supervisor spec and thus boot Linux.  You may have luck getting Microblaze or OpenRISC going.
