### ISSUE TITLE
xula2 on windows 10 driver problem

### ISSUE THREAD

**Issue by cambazz** [xesscorp/XuLA2#8]
Hello,

When I try to install the driver for the xula2 board (by going to hardware manager, right clicking on the xula board, and selecting "update driver software", windows gives the following error:

![screenshot 119](https://cloud.githubusercontent.com/assets/293859/24905218/dcaa9db8-1ebb-11e7-872b-8d15804a253b.png)

Any ideas how I can fix this problem?

Best regards,
C.

**Comment by xesscorp** [comment]
The XuLA2 uses the libusb-win32 driver. The installer should install this, but some people need to do it manually. Here are the instructions for doing that:

The XSTOOLs installer places a utility called zadig.exe in the C:\Programs (x86)\XSTOOLs\libusb-win32 directory. Once you have the XSTOOLs installed, run the zadig.exe program and then plug in your XSUSB board. Then just 1) select the libusb-win32 driver and 2) click on the Install Driver button. Then the driver should be installed.

**Comment by cambazz** [comment]
Hello, I managed to install the driver, but none of the programs will start. For example the test program. I tried executing from command line, and it will give no error, and no output.

Any ideas?

Best regards,
C.

**Comment by Bharatcs** [comment]
Same problem in win 10 ,even after installing libusb-win32 driver. None of the program will start.
